Tests for luagit2
SatyendraBanjare/luagit2 pull request #1
Opened 2018-06-03 15:48 UTC by SatyendraBanjare

Added lua Tests for the functions of modules written so far. 
Also created a main test file so as to allow running all tests fron a single execution

2018-06-09 16:41 UTC, Etiene requested changes
Wow, this was a big PR! Good work! 

Do you want to pair program to go through the comments together? :) (Some of the comments apply to multiple parts)

Could you make smaller PRs next time? For example, this one could have been broken into a PR for the commit tests, one for the config tests, etc. That makes it easier to review!

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_main_test.lua
> +os.execute("git clone https://github.com/SatyendraBanjare/Simple-Repository.git")
Try not to depend on an external repository or to add git itself as a dependency.
People do all sort of weird things and might not have git installed since git itself is not a requirement for using libgit2. 

Two possible ways of doing this:

1 - using luagit2 itself to create a repo. 
2 - commit it to this repository. For doing that, you could do like libgit2 does. Their test repos are in subfolders but the `.git` directory inside the test repos are named `.gitted` so it doesn't conflict with the main dir. Then when the test runs, they are temporarily renamed to `.git`again.

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_main_test.lua
> +lib = require"luagit2"
Missing `local` before lib.

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_main_test.lua
> +lunatest = require "lunatest"
missing `local` before lunatest

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	repo = lib.luagit2_repository_open("./Simple-Repository")
missing `local` before repo

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	commit_id = lib.luagit2_oid_fromstr("bb300684ed4da2e11104a98ff4d825d81787ad3a")
Missing lots of locals in different places :) 
You can use a library called `luacheck`: https://luarocks.org/modules/mpeterv/luacheck
It is a linter for Lua and it will point some small problems like these accidental global variables.

What is your text editor? It might be even possible to integrate with it

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_string(commit_body_is_not_nil)
How do you know if the body is the expected string?

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	commit_id_nil_body = lib.luagit2_oid_fromstr("bb300684ed4da2e11104a98ff4d825d81787ad3a")
Many of the test information is used in different tests and there's a lot of repetition. 
For example, you could open the repo only once before the tests.
 
Additionally, you need to call `luagit2_repository_free` after you finish using the repo in the test or you might get some memory leaks. 

The easiest way to do this, is by using some test helpers like `setup`, `beforeAll`, `afterAll`, `tearDown`, etc. The names can vary between different test libraries. I tried looking up for the api of lunatest and I couldn't find. Could you send it to me? If it doesn't provide these options, then I would recommend switching to a different test library that offers that, like busted  (http://olivinelabs.com/busted/)

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_string(commit_message)
How do you know it's the message you expect?

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_string(commit_message)
One thing you can do is use luagit2 itself to create a commit from variables before the tests. That way you can compare it with the message stored.

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_nil(commit_message_enc) -- there is no encoding to the message so it should be nil.
You should also test when it has an encoding :)

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_string(commit_message_raw)
See comments above about generating the commits for the tests :)

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_not_nil(ancestor_commit)
See comments above about generating the commits for the tests :) 
You need to know it returns the correct commit, not just a value different from null!

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_not_nil(parent_commit)
Same!

2018-06-09 16:41 UTC, Etiene commented on tests/luagit2_libgit_test.lua
> +function luagit2_libgit_tests.test_luagit2_version()
This looks much better 👍

2018-06-09 18:57 UTC, SatyendraBanjare commented
Thankyou so much mam for reviewing :smiley:

2018-06-09 19:06 UTC, SatyendraBanjare commented on tests/luagit2_commit_test.lua
> +	commit_id = lib.luagit2_oid_fromstr("bb300684ed4da2e11104a98ff4d825d81787ad3a")
thanks I'll do so.

2018-06-10 10:46 UTC, SatyendraBanjare commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_string(commit_message)
@Etiene   this was example commit it I directly used from that example git repository(Sample-Repository) commits thus I knew it. 

Anyway I'll try to use luagit2 to first initialize things(an empty repository with example commits ) and then perform tests.

2018-06-10 10:46 UTC, SatyendraBanjare commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_nil(commit_message_enc) -- there is no encoding to the message so it should be nil.
Alright thanks :smiley:

2018-06-10 10:46 UTC, SatyendraBanjare commented on tests/luagit2_main_test.lua
> +os.execute("git clone https://github.com/SatyendraBanjare/Simple-Repository.git")
ok. Thankyou :smiley:

2018-06-10 10:46 UTC, SatyendraBanjare commented on tests/luagit2_libgit_test.lua
> +function luagit2_libgit_tests.test_luagit2_version()
thanks :smiley:

2018-06-10 10:46 UTC, SatyendraBanjare commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_not_nil(ancestor_commit)
@Etiene I guess I need more helper methods to actually get correct commit details for testing this functions. I'll try to look for similiar  things in future. thanks

2018-06-13 11:03 UTC, Etiene commented on tests/luagit2_commit_test.lua
> +	lunatest.assert_string(commit_message)
Ok!

2018-07-03 16:10 UTC, Etiene commented
Can this PR be closed now that you made a new PR for different tests using Busted?

2018-07-03 16:49 UTC, closed without merging